name: unit tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  push-pr-unit-tests:
    name: unit tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      python-version: ${{ matrix.python-version }}
  build-and-release:
    name: Release to Pypi
    needs: push-pr-unit-tests
    if: github.event_name == 'push' && github.repository == 'labgrid-project/pyserial'
    uses: ./.github/workflows/build-and-release.yml
    secrets: inherit
