name: reusable unit tests

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
      branch:
        type: string
        required: false

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, software]
    continue-on-error: false
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.branch }}
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml', 'requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install python dependencies
      run: |
        python -m pip install --require-hashes --no-deps -r requirements-dev.txt
    - name: Install Pyserial
      run: |
        pip install -e "."
    - name: Test with unittests
      run: |
        cd test
        python3 run_all_tests.py
